site_name: CrawJUD-Reestruturado
repo_url: https://github.com/seu-usuario/CrawJUD-Reestruturado
nav:
  - Início: README.md
  - Estrutura do Projeto: PROJECT-STRUCTURE.md
  - API:
      - Visão Geral: api/readme.md
      - Addons: api/addons/readme.md
      - Models: api/models/readme.md
  - Celery App:
      - Visão Geral: celery_app/readme.md
      - Addons: celery_app/addons/readme.md
      - Exceptions: celery_app/exceptions/readme.md
      - Resources: celery_app/resources/readme.md
      - Tasks: celery_app/tasks/readme.md
      - Types: celery_app/types/readme.md
  - CrawJUD:
      - Visão Geral: crawjud/readme.md
      - Addons: crawjud/addons/readme.md
      - Bots: crawjud/bots/readme.md
      - Core: crawjud/core/readme.md
      - Exceptions: crawjud/exceptions/readme.md
      - Types: crawjud/types/readme.md
  - SocketIO Server:
      - Visão Geral: socketio_server/readme.md
      - Addons: socketio_server/addons/readme.md
      - Constructor: socketio_server/constructor/readme.md
      - Domains: socketio_server/domains/readme.md
      - Namespaces: socketio_server/namespaces/readme.md
      - Types: socketio_server/types/readme.md
  - Variáveis de Ambiente:
      - API/CrawJUD: crawjud/ENVIRONMENT-VARIABLES.md
      - Celery: celery_app/resources/ENVIRONMENT-VARIABLES.md
