try {
    # Executa o pre-commit e captura a saída
    $preCommitOutput = pre-commit run --all-files 2>&1

    # Formata a saída como Markdown corretamente
    $markdownOutput = @"
\`\`\`\bash
$preCommitOutput
\`\`\`\
"@

    # Salva no arquivo Markdown
    $markdownOutput | Out-File -Encoding utf8 pre-commit-output.md

    # Exibe a saída formatada no terminal
    Write-Output $markdownOutput
} catch {
    Write-Error "Erro ao executar o pre-commit: $_"
    exit 1
}
# SIG # Begin signature block
# MIII3wYJKoZIhvcNAQcCoIII0DCCCMwCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUNvMJ1prJnHs0rQV6O2fnUj7U
# /NOgggZCMIIGPjCCBSagAwIBAgITHgAAFc8Diq7Jp7oElgAAAAAVzzANBgkqhkiG
# 9w0BAQsFADBPMRgwFgYKCZImiZPyLGQBGRYIaW50cmFuZXQxEzARBgoJkiaJk/Is
# ZAEZFgNmbXYxHjAcBgNVBAMTFWZtdi1TUlYtQVNHQVJELURDMi1DQTAeFw0yNTAx
# MjcxMzE2MTVaFw0yNjAxMjcxMzE2MTVaMGoxGDAWBgoJkiaJk/IsZAEZFghpbnRy
# YW5ldDETMBEGCgmSJomT8ixkARkWA2ZtdjERMA8GA1UECxMIVVNVQVJJT1MxDTAL
# BgNVBAsTBFQuSS4xFzAVBgNVBAMTDk5pY2hvbGFzIFNpbHZhMIIBIjANBgkqhkiG
# 9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3pwJk4jhWlf5ODpeju0mChIwuPYa4w8hoQRS
# AgoiIb6qSMlV59DG4DzUAn8SXoRF0h9Bj5AtFXGnKNwLfZ9eRAEsuq0C2dn3l2+m
# fOIBnxeopUCFTEEDnZE3WV18NVRTgBfx3R+Shvzv9HYuG7oX8ilaZ6T0XEmoyjjI
# VqeY45QAsQkr35Zjk/ZHb/Py0FuMZRTff1TqERt0y9Mm4QhrTUB0WqRha/Orw3RA
# /t6NIkB+p8Yj4BH/du11IDX40z1DGpPlcqjntbunotH0FeAgZeA0BIq9i3/mTBG9
# 1qERmLrEjXCJtPSdgt+qZtz+BMWAXS3XvOtpo8qTmGGerRed5QIDAQABo4IC9jCC
# AvIwJQYJKwYBBAGCNxQCBBgeFgBDAG8AZABlAFMAaQBnAG4AaQBuAGcwEwYDVR0l
# BAwwCgYIKwYBBQUHAwMwDgYDVR0PAQH/BAQDAgeAMB0GA1UdDgQWBBTMYK1Vnls3
# sYrMWNFQif4QG3fO/TAfBgNVHSMEGDAWgBQHujZf+/2B9+kUeELE3EIsMzGpbTCB
# 2wYDVR0fBIHTMIHQMIHNoIHKoIHHhoHEbGRhcDovLy9DTj1mbXYtU1JWLUFTR0FS
# RC1EQzItQ0EsQ049U1JWLUFTR0FSRC1EQzIsQ049Q0RQLENOPVB1YmxpYyUyMEtl
# eSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9Zm12
# LERDPWludHJhbmV0P2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3Q/YmFzZT9vYmpl
# Y3RDbGFzcz1jUkxEaXN0cmlidXRpb25Qb2ludDCB/QYIKwYBBQUHAQEEgfAwge0w
# gbUGCCsGAQUFBzAChoGobGRhcDovLy9DTj1mbXYtU1JWLUFTR0FSRC1EQzItQ0Es
# Q049QUlBLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENO
# PUNvbmZpZ3VyYXRpb24sREM9Zm12LERDPWludHJhbmV0P2NBQ2VydGlmaWNhdGU/
# YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MDMGCCsGAQUF
# BzABhidodHRwOi8vU1JWLUFTR0FSRC1EQzIuZm12LmludHJhbmV0L29jc3AwNgYD
# VR0RBC8wLaArBgorBgEEAYI3FAIDoB0MG25pY2hvbGFzLnNpbHZhQGZtdi5pbnRy
# YW5ldDBOBgkrBgEEAYI3GQIEQTA/oD0GCisGAQQBgjcZAgGgLwQtUy0xLTUtMjEt
# NjIzMTQyOTQxLTM4NTI4ODkxMjMtMTQyNDU1NDMxNy0xMTQyMA0GCSqGSIb3DQEB
# CwUAA4IBAQAcV5i+NSeaIjJTPk8LCDhMJ2rjH2jS65IVP0l7DZPGEcNWbs8+3ify
# /3yM/fa6nmIsD7bylGcq2hHATMn1pmWDs7fJrCwt8DBq20eu3F6wqo4bzOkI/d06
# xAx7xl/sNbQhoSRuawlpt9i+hiAe/IN6W+HGIrVt/5WxIlzOG8MCCwWvTfjMkfGu
# GdB3gOvtQ+d3WBziLrIN2URlEfoZB9M+T5Zx15Lu7aOoCgrMOy4wduK7qy5prb73
# nxdKAUvgbs9Jb8k0VsiJRxCDObZVIJHGl5xd3/YOtEH4HJ1OkZDOZoWOj8YTo368
# 2Q5rouOv+H8XV652LZI5kndwEUHAmyFRMYICBzCCAgMCAQEwZjBPMRgwFgYKCZIm
# iZPyLGQBGRYIaW50cmFuZXQxEzARBgoJkiaJk/IsZAEZFgNmbXYxHjAcBgNVBAMT
# FWZtdi1TUlYtQVNHQVJELURDMi1DQQITHgAAFc8Diq7Jp7oElgAAAAAVzzAJBgUr
# DgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMx
# DAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkq
# hkiG9w0BCQQxFgQUeolaurkXtr50NxKanAxAoDTsx6UwDQYJKoZIhvcNAQEBBQAE
# ggEAPsbBOvA8zSi8+RhA2Vch6B4MLWk3aKin0RN6+/LrCBd/vS0lr7ZoaRUnxb11
# R2dJ3miweDxLyJ33Vd1OSh5d1N1TbwzhoBtXRUF3BHCH536+oSmSkuhVqap2aY1N
# BIi+9BSc+6J0olWOW10pcf3LV6qj2PlpHvTi0g3U3diTe/ZjDrcZbW5rkmIZa1+0
# SZ32PHiAUwCs/3OREs9yHqlP+hmCqUw4SKDNk8GugMT8aJ/toruWDyAOqoMsQ+Cr
# YvpWbx9me3s4N2Vgd7tvdcCZt4SdvF4V9OeSU1yn5tiTuwYIYd7zBNGgFN6FG1zb
# GsCvMKsF/URHvjs1UgfuNXRDHA==
# SIG # End signature block
